apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: lwluster
  region: ap-south-1

nodeGroups:
   - name: ng1
     desiredCapacity: 1
     instanceType: t2.micro
     ssh:
        publicKeyName: firstkey
   - name: ng2
     desiredCapacity: 1
     instanceType: t2.small
     ssh:
        publicKeyName: firstkey
   - name: ng-mixed
     minSize: 1
     maxSize: 3
     instancesDistribution:
       maxPrice: 0.017
       instanceTypes: ["t3.small", "t3.medium"] # At least one instance type should be specified
       onDemandBaseCapacity: 0
       onDemandPercentageAboveBaseCapacity: 50
       spotInstancePools: 2     
     ssh:
         publicKeyName: firstkey
